version: '3'
services:
#  build:
#    image: maven:3.3.9-jdk-8
#    volumes:
#      - ~/.m2:/root/.m2
#      - .:/usr/src/working_dir
#    working_dir: /usr/src/working_dir
#    command: mvn clean install
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: movies_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/main/resources/config/mysql/conf:/etc/mysql/conf.d:ro
      - ./src/main/resources/config/mysql/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
  web:
    build: .
    links:
     - db
    volumes:
    - ~/jde/docker/tomcat/logs:/usr/local/tomcat/logs
    ports:
     - "8080:8080"
     - "8000:8000"
    environment:
      APP_ENV: container
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket